version: '3.0'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - mytb-data:/data
      - mytb-logs:/var/log/thingsboard

  counterfit:
    image: "hungldvntts/counterfit-iot:latest"
    container_name: counterfit
    ports:
      - "5000:5000"  # Mở port 9091 trên host, kết nối với port 9090 trong container
    networks:
      - default

volumes:
  mytb-data:
    external: true
  mytb-logs:
    external: true
